@BASE_URL=http://localhost:8001/api/user
@CONTENT_TYPE=Content-Type:application/json

### 获取用户表API
get {{ BASE_URL }}/get_user_list

### 注册API
post {{ BASE_URL }}/register
{{ CONTENT_TYPE }}

{
  "username": "xiaoyesensen",
  "password": "123456"
}

### 登录API
post {{ BASE_URL }}/login
{{ CONTENT_TYPE }}

{
  "username": "xiaoyesensen",
  "password": "123456"
}

### 获取个人信息API
post {{ BASE_URL }}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjRmOTE5MzczODM2OTliMjU4N2ZjYiIsImlhdCI6MTY4MDE1NTY3NiwiZXhwIjoxNjgwMTU1NzM2fQ.L23UyDRd2QgQghCFV78VBv3BNqNUrREi7j_dURphecY